### ISSUE TITLE
Decryption problem running presto queries with AWS client side encryption using KMS

### ISSUE THREAD

**Issue by pandeyp** [awslabs/emr-bootstrap-actions#103]
Hi,

I have used your latest script that successfully installs presto server(version 0.99) and java 8 on Amazon EMR instance. My data files are located in a s3 bucket encrypted with client-side customer managed key that were encrypted . When I create a hive table that references those encrypted data files in s3, hive can successfully decrypt the records and display it in console. However, when viewing the same external table from presto command line interface the data is displayed in its encrypted form. I have looked at your link given in:
https://prestodb.io/docs/current/release/release-0.57.html and added those properties in my hive.properties file and it looks like given below.

hive.s3.connect-timeout=2m
hive.s3.max-backoff-time=10m
hive.s3.max-error-retries=50
hive.metastore-refresh-interval=1m
hive.s3.max-connections=500
hive.s3.max-client-retries=50
connector.name=hive-hadoop2
hive.s3.socket-timeout=2m
hive.s3.aws-access-key=AKIAJ********NQ
hive.s3.aws-secret-key=UMo******46t3M/ILIO********5pHj
hive.metastore.uri=thrift://localhost:9083
hive.metastore-cache-ttl=20m
hive.s3.staging-directory=/mnt/tmp/
hive.s3.use-instance-credentials=true

Any help on how to decrypt the files in using presto cli will be much appreciated.

**Comment by mombergm** [comment]
Hi. 
When using HIVE on EMR with data stored in S3, you are effectively using the EMRFS library to access S3. However, Presto does not utilize EMRFS and instead has its own implementation of an S3 handler. At the moment, the Presto S3 library does not support client side encryption and only supports S3 server side encryption at the moment.

**Comment by mombergm** [comment]
I'm closing this issue in favour of [2945](https://github.com/facebook/presto/issues/2945) in the Presto repository since this is a PrestoS3Filesystem issue.

**Comment by mombergm** [comment]
I'm closing this issue in favour of [2945](https://github.com/facebook/presto/issues/2945) in the Presto repository since this is a PrestoS3Filesystem issue.
