### ISSUE TITLE
Unable to set grantees for output files in S3 using spark-submit

### ISSUE THREAD

**Issue by jsteigel-rmn** [awslabs/emr-bootstrap-actions#118]
I'm trying to use spark-submit to run a python spark job and pass in the fs.s3.canned.acl as a --conf option like this:

    hadoop jar /mnt/var/lib/hadoop/steps/s-3HIRLHJJXV3SJ/script-runner.jar \
    /home/hadoop/spark/bin/spark-submit --deploy-mode cluster --master yarn-cluster \
    --conf "spark.driver.extraJavaOptions -Dfs.s3.canned.acl=BucketOwnerFullControl" \ 
    hdfs:///user/hadoop/spark.py

The job runs fine and the files appear in the correct s3 bucket but when I look at the permissions of the files, there aren't any grantees on it.

I've also tried in the spark.py script adding:
    conf = SparkConf().set('spark.driver.extraJavaOptions', '-Dfs.s3.canned.acl=BucketOwnerFullControl')
    sc = SparkContext(conf=conf)

But the grantees on the files still do not get set.

**Comment by christopherbozeman** [comment]
This property needs to be set in the Hadoop configuration in order for the
setting to take effect. The easiest way would be to do:
sc.hadoopConfiguration.set("fs.s3.canned.acl","BucketOwnerFullControl")

Or set it in the core-site.xml by configure-hadoop on EMR (
http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-plan-bootstrap.html#PredefinedbootstrapActions_ConfigureHadoop
).

**Comment by jsteigel-rmn** [comment]
Thanks, I figured that out last night and I should've closed this out then.  The 'gotcha' that I ran into is that in python, you don't have direct access to the hadoop configuration.  You have to get the JavaSparkConfig first:
sc._jsc.hadoopConfiguration().set("fs.s3.canned.acl","BucketOwnerFullControl")

Thanks for your help!
