### ISSUE TITLE
Ganglia unresponsive after many resize operations?

### ISSUE THREAD

**Issue by jkleckner** [awslabs/emr-bootstrap-actions#132]
I don't know if it was all of the resizing operations or not, but ganglia in a dev cluster became slower and slower until unresponsive at some point.  This may be because it retained perhaps > 150 "lost nodes" that were the result of resizing up/down.

Has anyone else seen this?  I tried blindly restarting gmond and gmetad but that didn't heal it.

For the record the cluster is 1.2.1 Spark with AMI 3.3.2

**Comment by christopherbozeman** [comment]
Ganglia doesn't handle resizes automatically and likely the php memory default allocated is no longer sufficient.  This may help http://linuxtoolkit.blogspot.com/2011/11/removing-node-from-ganglia-web-frontend.html.   Also, when bouncing Ganglia in AMI < 3.4.0 make sure to provide a `-c` to point to the config files for gmond.conf and gmetad.conf located at /etc.  These earlier AMIs will not restart Ganglia correctly if using the init.d or service scripts.

**Comment by jkleckner** [comment]
Thanks for the response.  ```Ganglia doesn't handle resizes automatically``` sort of means that EMR doesn't really handle Ganglia for task nodes, true?  Would it be reasonable to include a workaround like you mention in that link by setting some default for ```host_dmax``` so that old nodes would get removed?  Perhaps 4 hours or some such?
```
globals { 
host_dmax = 14400 
}
```
Or perhaps make it easy to set a value on creation?

We have moved on to AMIs >= 3.7

**Comment by christopherbozeman** [comment]
The workaround makes sense though I have not tested.  I've also filed this improvement request internally.
