### ISSUE TITLE
spark saveAsTextFile make two results

### ISSUE THREAD

**Issue by landvibe** [awslabs/emr-bootstrap-actions#135]
AMI version 3.8.0
Spark version 1.3.1

My python code is very simple. It should make one result at s3n://landvibe-emr/spark/result/simple_test_(number).
But there are two output folders like below.
s3n://landvibe-emr/spark/result/simple_test_253103
s3n://landvibe-emr/spark/result/simple_test_897893
And the status of the step is failed.
When I run this code without EMR, it generates one result folder.

*my cli command
aws emr create-cluster --name Spark --ami-version 3.8.0 --instance-type=m3.xlarge --instance-count 2 --use-default-roles --ec2-attributes KeyName=podotree-landvibe --log-uri s3://landvibe-emr/spark/log --bootstrap-actions Name=Spark,Path=s3://support.elasticmapreduce/spark/install-spark,Args=[-x] --steps Name=SparkPi,Jar=s3://ap-northeast-1.elasticmapreduce/libs/script-runner/script-runner.jar,Args=[/home/hadoop/spark/bin/spark-submit,--deploy-mode,cluster,s3://landvibe-emr/spark/code/simple_test.py] --auto-terminate

*simple_test.py
from pyspark import SparkContext
import random
sc = SparkContext("local", "testapp")
lines = sc.textFile("s3n://landvibe-emr/input/2015-06-29-00/t_open_log", sc.defaultParallelism * 3)
randValue = random.randrange(100,1000000)
lines.saveAsTextFile("s3n://landvibe-emr/spark/result/simple_test_"+str(randValue))
sc.stop()

**Comment by christopherbozeman** [comment]
This is likely caused by conflicting master modes.   The spark-submit is using yarn-cluster but your code is using local.  Try:
'''
sc = SparkContext(appName="testapp")
'''
