### ISSUE TITLE
how to run an application with multiple python files

### ISSUE THREAD

**Issue by landvibe** [awslabs/emr-bootstrap-actions#136]
AMI version 3.8.0
Spark version 1.3.1

My spark program has multiple python files.
And I use --py-files option to load the files.
It works well on custom spark cluster (without EMR).
But in the case of EMR it fails to import python files.

for example, I have two python files (test1.py, test2.py)
*test1.py is like below
import test2   ==> here the EMR step fails
I want to know how to run the application with multiple python files.

*this is my emr cli
aws emr create-cluster --name Spark --ami-version 3.8.0 \
--instance-type=m3.xlarge --instance-count 2 \
--use-default-roles --ec2-attributes KeyName=podotree-landvibe \
--log-uri s3://landvibe-emr/spark/log \
--bootstrap-actions Name=Spark,Path=s3://support.elasticmapreduce/spark/install-spark,Args=[-x] \
Name=install_es,Path=s3://landvibe-emr/spark/bootstrap-actions/install_python_elasticsearch.sh \
--steps Name=SparkPi,Jar=s3://ap-northeast-1.elasticmapreduce/libs/script-runner/script-runner.jar,Args=[/home/hadoop/spark/bin/spark-submit,--deploy-mode,cluster,s3://landvibe-emr/spark/code/test1.py,--py-files,s3://landvibe-emr/spark/code/test2.py] \
--auto-terminate

**Comment by christopherbozeman** [comment]
Spark has had a number of bugs around distributing supporting files in Yarn cluster mode (for example, https://github.com/apache/spark/pull/6360).    For Spark 1.3.1 and 1.4.0 I've had the best experience getting this to work by zipping all the additional python files the providing to "--py-files s3://bucket/prefix/mymodules.zip".

**Comment by saran049** [comment]
Even I am working on similar kind of problem where I need to import from multiple python files to run my python script. So, how did you find you find a way to add the dependency files to the EMR scripts?

Thanks in advance
