### ISSUE TITLE
How to run instances with Spark 1.3.1 built on Hadoop 2.6 ?

### ISSUE THREAD

**Issue by tfournier314** [awslabs/emr-bootstrap-actions#137]
Hi,

I tried to run a bootstrap action on EMR in order to install Spark 1.3.1 built on Hadoop 2.6 (and not 2.4).

1- Is it possible ?

2- If so, my conf file specify a repository where you can find spark-1.3.1-bin-hadoop2.6.tgz and I'm using the setting "-v 2.6.0" (see details here https://github.com/awslabs/emr-bootstrap-actions/blob/master/spark/README.md).

My conf file:

default default python s3://support.elasticmapreduce/spark/install-spark-script.py s3://<my_repository>/spark-1.3.1-bin-hadoop2.6.tgz s3://support.elasticmapreduce/spark/maximize-spark-default-config

Nonetheless, it's still not working...

Thanks for you help.

Regards

Thomas

**Comment by jkleckner** [comment]
The version file doesn't indicate that it is supported:
https://github.com/awslabs/emr-bootstrap-actions/blob/master/spark/VersionInformation.md

**Comment by christopherbozeman** [comment]
The Hadoop version is dependent on the underlying Hadoop install by EMR.   So until EMR releases with Hadoop 2.6.0 it will need to remain on Hadoop 2.4.0.    Watch the Forum Announcements (https://forums.aws.amazon.com/forum.jspa?forumID=52) for info on releases.
