### ISSUE TITLE
Add support for Dynamic allocation & cluster resizing in the install-spark

### ISSUE THREAD

**Issue by mkanchwala** [awslabs/emr-bootstrap-actions#138]
Add support for the dynamic allocation and cluster resizing support of EMR in install-spark switch -x.

Also would like to have the 75 - 80 % resources utilization of the EMR cluster using yarn-cluster as Master in Spark-Job, Currently I've seen only 20% of utilization http://ec2-publicdns:9026/cluster/scheduler

Also would like to have a workaround on TASK instances for the same

**Comment by mkanchwala** [comment]
Currently install spark -x is updating this properties only :

spark.executor.instances
spark.executor.cores
spark.executor.memory

**Comment by mkanchwala** [comment]
https://github.com/awslabs/emr-bootstrap-actions/blob/master/spark/maximize-spark-default-config

**Comment by mkanchwala** [comment]
Comments Plz? How can I achieve this?

**Comment by christopherbozeman** [comment]
Dynamic resource allocation requires additional setup that is beyond the Spark bootstrap action. This is built into Spark on EMR starting with release 4.0.0 (see http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-spark-configure.html#spark-dynamic-allocation).  

As for the other comments, Spark on EMR does work if number of executors is higher than core nodes. The Spark bootstrap action has a constraint that it only counts the initial core instances when using -x.

**Comment by parvez99** [comment]
Hi christopherbozeman
I am using an AWS EMR cluster for running several Hadoop Jobs.
Config: AMI: 3.9.0
1 Master 1 Core node
Apps : Hive Pig Spark 1.4.1.a 


To Do: I want to resize the cluster based on the workload. 
Done: I have written a script to add task nodes inside a running cluster. I am able to resize the cluster ( both addition and removal of task nodes ) successfully.

Problem: When I add a task node ( say for 15minutes ) , the task node is used for 15 minutes for executing tasks. But at the time of Decommissioning the Task Node after 15mins, if the task node has some workload running, then the whole exection gets stuck. ie: The Task Node Ec2 instance is terminated even if there is workload running on it..


What I want: If there was a way I could identify that "if there is workload running on a Task node, then delay its Decommissioning for few more minutes. That would ensure completion of existing application running on the task node and then terminate it"

Please help. Thank you

**Comment by julienbaley** [comment]
@parvez99 can you use yarn.resourcemanager.decommissioning.timeout ?
