### ISSUE TITLE
Spark Bootstrap action : User-Provided library not added while using Yarn-Cluster mode

### ISSUE THREAD

**Issue by mkanchwala** [awslabs/emr-bootstrap-actions#143]
When I added custom jars of mine from S3 to my cluster using -u switch, while running in yarn's cluster mode it doesn't appears any of'em

**Comment by christopherbozeman** [comment]
You are correct, it just makes them available to the driver if ran in client mode.  Just add look local file references to --jar on spark-submit.

**Comment by mkanchwala** [comment]
@christopherbozeman : Ok, I used spark-submit script with the cluster mode but It thrown me the same error of ClassNotFound. 

So Ill suggest that when using the -u switch in the Spark Bootstrap action, the user-provided library should also be included in the yarn's/hadoop's classpath.

For Now, I've to add a custom bootstrap action and manually copy the jars to the Master and Slave Nodes

**Comment by mkanchwala** [comment]
Added a Custom Bootstrap action to peform the same on all nodes
