### ISSUE TITLE
Hue for EMR -4

### ISSUE THREAD

**Issue by ankurmitujjain** [awslabs/emr-bootstrap-actions#149]
Hue is missing from new release of EMR, so will appreciate if you can create a bootstrap for installing Hue.

**Comment by mkanchwala** [comment]
Is there any update on this issue? I need it for my Hive Queries Monitoring and other Stuff!!!!

**Comment by christopherbozeman** [comment]
Thank you for the feedback.   Hue will be included in future releases of EMR 4.x.  Please watch https://forums.aws.amazon.com/forum.jspa?forumID=52&start=0 for announcements, though I cannot provide an ETA or specific release version.
