### ISSUE TITLE
Presto EMR 4.0.0

### ISSUE THREAD

**Issue by Downchuck** [awslabs/emr-bootstrap-actions#150]
It appears that the Ruby EMR library has been deprecated and so the commands calling it are no longer functioning. The data needed for the presto installation is minimal:
```
job_flow = Emr::JsonInfoFile.new('job-flow')
instance_info = Emr::JsonInfoFile.new('instance')
$is_master = instance_info['isMaster'].to_s == 'true'
$master_private_dns = job_flow['masterPrivateDnsName'].to_s
```

It's likely that this can simply be fetched from the instance endpoints, and the inclusion of emr/common can be removed. Note that endpoints have slightly changed, and so maintaining compatibility with both 3.x and 4.x may be difficult.

**Comment by Downchuck** [comment]
```
require 'rubygems'
require 'net/http'
require 'json'

metadata_endpoint = 'http://169.254.169.254/latest/user-data'
instance_info = JSON.parse( Net::HTTP.get( URI.parse( metadata_endpoint ) ) )
```

Still working on master private dns.

**Comment by Downchuck** [comment]
https://github.com/awslabs/emr-bootstrap-actions/blob/master/impala/impala-install

**Comment by mombergm** [comment]
Hi.
We do have a very early ALPHA version of a Presto BA for EMR 4.0.0. 
For the moment, until we can do some more testing, and confirm everything is working like expected, you can find the BA here: https://github.com/mombergm/emr-bootstrap-actions/tree/master/presto/EMR-4.0.0

**Comment by Downchuck** [comment]
@mombergm Date in the README.md is wrong (typo on month); What's with the "pstree" while loop?

Looks like they've just fixed more bugs in Hive integration in 0.115.

**Comment by mombergm** [comment]
Thanks for letting me know. I fixed the date  
The pstree was part of my debugging while I was making the changes, it's been removed now. 

You should be able to download 0.115 from prestodb.io and pass it as a custom binary using the bootstrap action

**Comment by Downchuck** [comment]
Confirmed latest @mombergm works with Presto 0.114 using ORC data on S3.

**Comment by istewart** [comment]
@mombergm We've been using Presto on EMR 4.0.0 successfully for a few days now, but new clusters are failing with: The supplied bootstrap action(s): 'install presto' are not supported by release 'emr-4.0.0'.

Any idea what's up?

**Comment by mombergm** [comment]
Hey!
I'm glad to hear you are using Presto on EMR 4.0.0 successfully. 
The EMR Service has made some changes to safeguard agianst BootStrap Actions that are not EMR 4.0.0 ready and have therefore blocked all BA's in the s3://support.elasticmapreduce/bootstrap-actions/* location. 

The new location for the BA that should still work can be found here: s3://support.elasticmapreduce/release/4.x/presto/presto-install

**Comment by Downchuck** [comment]
@mombergm would you bump the version on that new presto-install -- it has the pstree while loop which will eat up disk space.

**Comment by mombergm** [comment]
Thanks for pointing that out @Downchuck. I've bumped it. pstree should now be gone. 
Please let me know if you find any other issues?

**Comment by christopherbozeman** [comment]
Presto now bundled with emr release 4.1.0. https://forums.aws.amazon.com/ann.jspa?annID=3279
