### ISSUE TITLE
EMR 4 External Hive Metastore

### ISSUE THREAD

**Issue by ankurmitujjain** [awslabs/emr-bootstrap-actions#152]
Does anyone knows how to create an emr 4.0 cluster with Hive Meta-store stored in external RDS/MySQL

**Comment by mombergm** [comment]
You can configure the Hive Metastore location by changing the correlating properties in the hive-site.xml. On EMR 4.0.0 this is located in /etc/hive/conf/

Please reference the Hive Documentation for which properties to modify [here](https://cwiki.apache.org/confluence/display/Hive/AdminManual+MetastoreAdmin#AdminManualMetastoreAdmin-RemoteMetastoreDatabase)

Please also note that EMR 4.0.0 uses Hive 1, which has a different Database Schema from previous EMR versions: Starting in release 0.12, Hive also includes an off-line schema tool to initialize and upgrade the metastore schema. Please refer to the details [here](https://cwiki.apache.org/confluence/display/Hive/Hive+Schema+Tool)

**Comment by ankurmitujjain** [comment]
Thanks @mombergm I had tried steps mentioned in EMR Documentation guide. I also tried 
[Configure Apps](http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-configure-apps.html) as below, and tried to set MY_HIVE_SITE_FILE=s://bucket/hive-site.xml but that too not working.

![image](https://cloud.githubusercontent.com/assets/1140475/9112372/cddb7ba6-3c6b-11e5-9a68-9a40780f6332.png)
I like to do this as part of bootstrap action instead of doing it after cluster creation.
I dont have any dependencies with previous version of Hive. As I am starting from scratch...

**Comment by ankurmitujjain** [comment]
@mombergm 

I dont see any option like I use to have in previous release to define my hive-site.xml

```
--bootstrap-actions Name="Install Hive Site Configuration",Path="s3://elasticmapreduce/libs/hive/hive-script",\
Args=["--base-path","s3://elasticmapreduce/libs/hive","--install-hive-site","--hive-site=s3://mybucket/hive-site.xml","--hive-versions","latest"]
```

**Comment by mkanchwala** [comment]
Please find the steps for the Hive Metastore setup on RDS : 

Add this Configuration in Edit Software Settings Tab :

[{"classification":"hive-site","properties":{"javax.jdo.option.ConnectionUserName":<YOUR_MYSQL_USER>,"javax.jdo.option.ConnectionDriverName":"com.mysql.jdbc.Driver","javax.jdo.option.ConnectionPassword":<YOUR_MYSQL_PASSWORD>,"javax.jdo.option.ConnectionURL":<YOUR_CONNECTION_URL>}}]

**Comment by ankurmitujjain** [comment]
Thanks @mkanchwala , this resolved problem....

**Comment by rraghuram64** [comment]
Hello,

I am trying to do the same thing with the latest version of EMR and the cluster is terminating with bootstrap failures.

Any help would be appreciated.

Thanks

**Comment by christopherbozeman** [comment]
For 4.x releases do not explicitly define javax.jdo.option.ConnectionDriverName property, let the default driver name apply. In 4.1.0 this changed to a MariaDB connector which us compatible with MySQL.

**Comment by rraghuram64** [comment]
I tried the same and its failing when you don't specify that property.

**Comment by christopherbozeman** [comment]
@rraghuram64 please provide a clsuter id (j-###) that exhibits the problem.

**Comment by rraghuram64** [comment]
I think this is the one j-1ATVZDZNPRBKE failed when I removed the mentioned parameter and was unable to connect to the external metastore.

**Comment by rraghuram64** [comment]
@christopherbozeman I removed the mentioned property but still the cluster is terminating with some bootstrap failures.Here is the cluster Id that I tried j-MF0HZXV9HEKL                       [{"classification":"hive-site","properties":{"javax.jdo.option.ConnectionUserName":"root","javax.jdo.option.ConnectionPassword":"hivetest","javax.jdo.option.ConnectionURL":"jdbc:mysql://hive.cckyyg5sffpl.us-east-1.rds.amazonaws.com:3306/metastore?createDatabaseIfNotExist=true"}}]

**Comment by christopherbozeman** [comment]
@rraghuram64  Thanks for the feedback, I opened an outbound support case 1555886611 so we can resolve the issue together.   Please visit https://aws.amazon.com/support and login with the same account as the cluster was created with.

**Comment by rraghuram64** [comment]
@christopherbozeman Thanks for the help.I resolved the issue.

**Comment by dapeng-fu** [comment]
Is the issue fixed in emr-4.2.0 ? My configuration is '[
  {
    "Classification": "hive-site",
    "Properties": {
      "javax.jdo.option.ConnectionURL": "jdbc:mysql://xxx:3306/xxx?createDatabaseIfNotExist=true",
      "javax.jdo.option.ConnectionUserName": "xxx",
      "javax.jdo.option.ConnectionPassword": "xxx"
    }
  }
]',  but got "application provisioning failed".

**Comment by christopherbozeman** [comment]
There is not a problem with the release, the issues addressed in this thread have been configuration related.  What's a cluster id (j-####) I can review?

**Comment by dapeng-fu** [comment]
Cluster id is "j-1CLHKLBPWCE1E" .

**Comment by christopherbozeman** [comment]
@dapeng-fu the error from schema tool is this (removing actual IP):

Caused by: org.mariadb.jdbc.internal.common.QueryException: Could not connect to address=(host=X.X.X.X)(port=3306)(type=master) : Connection timed out

Thus I would check security groups and such configs to ensure that where ever this DB resides has can be reached by master instance.   One test would be to start cluster without custom metastore db and then use "mysql -h X.X.X.X ..." style command to networking connectivity from master.

**Comment by zachahuy** [comment]
@dapeng-fu Not sure if you are still having this issue, but I spent several hours with the same problem you got and found out that the config file some how encoded the "=" . The best way to see this is by cloning the fail to bootstrap cluster and then click back on the config page to see what is the entire JSON.

**Comment by arunrbongale** [comment]
Hi All,
can we store the hive metadata on to dynamodb.

**Comment by handsetvn** [comment]
How to connect a Presto database to MySQL ?
