### ISSUE TITLE
Ganglia on EMR 4

### ISSUE THREAD

**Issue by ankurmitujjain** [awslabs/emr-bootstrap-actions#153]
Hello Team,

Is there any bootstrap action we can use to install Ganglia?

Thanks
Ankur

**Comment by sid137** [comment]
{
    "Name": "Install Ganglia",
    "Path": "s3://elasticmapreduce/bootstrap-actions/install-ganglia"
  },

**Comment by mkanchwala** [comment]
![capture](https://cloud.githubusercontent.com/assets/4456210/9160834/99a8f3fc-3f5b-11e5-8431-0214eab6932f.PNG)


Ganglia is not supported on EMR 4 for now.

**Comment by florianverhein** [comment]
Is there an ETA on ganglia support for this EMR release?

**Comment by christopherbozeman** [comment]
Ganglia on EMR 4.x will be coming in a future release.   Unfortunately, I cannot share an ETA at this time but recommend watching https://forums.aws.amazon.com/forum.jspa?forumID=52&start=0 for future announcements.

**Comment by florianverhein** [comment]
closed as done or ...?

**Comment by christopherbozeman** [comment]
No, closed as this is not a bootstrap action issue.
