### ISSUE TITLE
Amazon EMR 3.8/4.0 - Hive 1.1 support for multiple versions using bootstrap action

### ISSUE THREAD

**Issue by mkanchwala** [awslabs/emr-bootstrap-actions#154]
Hi Guys,

I am looking for some option to have Hive 1.1 on Amazon 4.0 to work on with Spark engine, If it is not available can we add this to please?

https://forums.aws.amazon.com/thread.jspa?threadID=208848&tstart=0

Thanks

**Comment by mkanchwala** [comment]
Also can we have the same emr-bootstrap-action for the Hive to support multiple versions(Including the Latest one or upto 1.1)  in Amazon EMR 3.8.0 and Amazon EMR 4.0.0

**Comment by mkanchwala** [comment]
Guys, any updates on this phase. We are looking more on Hive on Spark engine and Hive 1.1 have this thing.

**Comment by christopherbozeman** [comment]
The Hive version on EMR is product of the EMR AMI and release version.  As of EMR release 4.0 the Hive version is Hive 1.0.0.  Please watch https://forums.aws.amazon.com/forum.jspa?forumID=52 for future announcements when later versions of Hive are available.   Also, forward development regarding native support for Spark on EMR will only be in the EMR releases and will not continue to be supported by the Spark bootstrap action installation (which was EMR AMI 3.x).
