### ISSUE TITLE
Add support for spark 1.4.1 with bootstrap action

### ISSUE THREAD

**Issue by l0n3r4n83r** [awslabs/emr-bootstrap-actions#157]
We want to use spark 1.4.1 on EMR clusters launched through Amazon DataPipeline but we can not specify EMR versions in datapipeline request. Current work around is to specify -v 1.4.0.a to the the bootstrap action but we want a 1.4.1 cluster. Is it possible to add this version ?

**Comment by mkanchwala** [comment]
I agree with the same, I also need the support for Spark 1.4.1 on the EMR 3.8.0 and I think that including the same tarball which is present in EMR 4.0 can help here, Also I would like to add the other switches like -x and etc. should also work with that distribution as these are not present in EMR 4.0.


Looking forward on the same.

**Comment by erond** [comment]
support suddenly shut down.  2+ months without even an answer!

**Comment by christopherbozeman** [comment]
A build for Spark 1.4.1 is now available for the EMR AMI 3.x using the Spark bootstrap by requesting version "1.4.1.a".   Please note this does not include the enhancements and fixes as found in EMR 4.x release and is being provided as a means to unblocking use-cases (such as the Data Pipeline not yet supporting EMR 4.x).     

As for the switches like -x found in the Spark BA (bootstrap action) for configuring Spark, these have been replaced with a more robust configuration method in EMR release 4.x (see http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-spark-configure.html).  The native Spark on EMR 4.x supports automatically configure executors with maximum resource allocation and the Spark Dynamic Resource Allocation models.

**Comment by erond** [comment]
Appreciated. Thank you @christopherbozeman !
