### ISSUE TITLE
Apache Drill - 404

### ISSUE THREAD

**Issue by evialle** [awslabs/emr-bootstrap-actions#16]
Hello,

When I execute the setup_drill, I get the following error on my amazon EMR:

curl: (22) The requested URL returned error: 404 Not Found
/mnt/var/lib/bootstrap-actions/4/setup_drill:23:in `run': Command failed: sudo curl -L --silent --show-error --fail --connect-timeout 60 --max-time 720 --retry 5 -O  http://beta.elasticmapreduce.s3.amazonaws.com/bootstrap-actions/zookeeper-standalone/zookeeper-3.4.5.tar.gz (RuntimeError)
   from /mnt/var/lib/bootstrap-actions/4/setup_drill:28:in `sudo'
   from /mnt/var/lib/bootstrap-actions/4/setup_drill:166:in `installZookeeper'
   from /mnt/var/lib/bootstrap-actions/4/setup_drill:218:in `installDrill'
   from /mnt/var/lib/bootstrap-actions/4/setup_drill:244

Regards,

Eric

**Comment by danosipov** [comment]
@evialle AMI 3.3.1 already has java-7 installed, so you can remove the lines that install it.
Check out my fork of the bootstrap actions: https://github.com/danosipov/emr-bootstrap-actions/tree/update_drill_versions

**Comment by stmcpherson** [comment]
is this resolved with the latest merge of the bootstrap?
