### ISSUE TITLE
Spark 1.5.0 support on EMR 3.x and EMR 4.x

### ISSUE THREAD

**Issue by mkanchwala** [awslabs/emr-bootstrap-actions#160]
Release Candidates for the Spark 1.5.x.

http://spark.apache.org/releases/spark-release-1-5-0.html

**Comment by abhibond** [comment]
Waiting for this release on EMR. Lots of feature updates that we want to use in our production pipelines.

**Comment by njvijay** [comment]
I need Spark 1.5.x support on EMR 4.x asap.

**Comment by MarioCerdan** [comment]
Same here! Spark 1.5 + EMR is gonna be the best! :)

**Comment by sixers** [comment]
Maybe someone can fork it and add support for 1.5?

It seems that we only needed  small changes in Spark itself to make 1.4.1 work on EMR:
https://github.com/apache/spark/compare/branch-1.4...christopherbozeman:bozemanc-v1.4.0.

Is this true for all previous releases?

**Comment by drudim** [comment]
+1 for the feature

**Comment by danoyoung** [comment]
+2 for the feature

**Comment by christopherbozeman** [comment]
Spark 1.5 on EMR is coming soon to release 4.x.   Please watch https://forums.aws.amazon.com/forum.jspa?forumID=52 for announcement.

**Comment by ankurmitujjain** [comment]
Cool :+1:

**Comment by MarioCerdan** [comment]
Hi everyone!

emr-4.1.0 has spark 1.5

yeeah

**Comment by christopherbozeman** [comment]
Spark 1.5 out with release 4.1.0. https://forums.aws.amazon.com/ann.jspa?annID=3279
