### ISSUE TITLE
HBase on EMR 4.0.0

### ISSUE THREAD

**Issue by takism1** [awslabs/emr-bootstrap-actions#161]
I would like to run HBase 0.98 on EMR 4.0.0. EMR only provides HBase (up to 0.94) on older versions.  

Installing 0.98 on EMR 3.x.x is possible with [these bootstrap scripts](http://stackoverflow.com/questions/32208549/how-to-use-newer-versions-of-hbase-on-amazon-elastic-mapreduce) but they don't work on 4.0.0.

I think such bootstrap scripts for 4.0.0 would be very useful if they were provided here.

**Comment by christopherbozeman** [comment]
Thank you for your comment.    HBase on EMR is not a bootstrap action but a native application on EMR.   Please watch https://forums.aws.amazon.com/forum.jspa?forumID=52&start=0 for future announcements regarding Hbase support in future releases.    AWS EMR hears your request for a later version of Hbase being natively supported on EMR.
