### ISSUE TITLE
AMI 3.9.0 SparkConfigure setting options on master but not task nodes?

### ISSUE THREAD

**Issue by jkleckner** [awslabs/emr-bootstrap-actions#177]
We have a 3.9.0 cluster that uses SparkConfigure to set log retention options as follows:
```
  --steps \
Name=SparkConfigure,Jar=s3://elasticmapreduce/libs/script-runner/script-runner.jar,Args=[s3://support.elasticmapreduce/spark/configure-spark.bash,spark.executor.logs.rolling.maxRetainedFiles=60,spark.executor.logs.rolling.strategy=time]
```
Those options are set on the master but not set on the task nodes.  Should they be set there as well?
The cluster id is j-4K2L3C6LWNZ9 if you want to look.

**Comment by christopherbozeman** [comment]
Spark on EMR is designed to run on YARN thus the logs are taken care of by the Yarn framework.
