### ISSUE TITLE
EMR Step: Submit Spark JAR from S3

### ISSUE THREAD

**Issue by m1racoli** [awslabs/emr-bootstrap-actions#23]
It would be very good to have a spark-submit script which can submit jars from S3 to the cluster and which can be executed as an EMR step (i.e. the script runner).

Inspiration:
s3://support.elasticmapreduce/.../emr-spark-submit
    --class CLASS --master yarn-client --num-executors 10 s3://bucket/path/to/my.jar [args]

That would make the deployment and execution of spark applications as easy as running Hadoop jars.

**Comment by m1racoli** [comment]
First of all THX for your examples and your general efforts.

It is true that the spark-submit script retrieves from S3, when the *master* is set to **yarn-cluster**. 

Unfortunately I use some steps in Java code, which require AWS credentials and thus failes when running in cluster mode, since the credentials are not available from within the yarn containers (please correct me, if I am wrong).

My solution for now is to deploy the jar locally on the master node and run as **yarn-client**.

Best

**Comment by christopherbozeman** [comment]
m1racoli - AWS credentials can be retrieved from within the yarn containers.   If the cluster is running with EC2 role it can retrieve a temporary credential from EC2 metadata (http://docs.aws.amazon.com/AmazonS3/latest/dev/AuthUsingTempSessionTokenJava.html) or if using root/IAM account could just retrieve it from the Hadoop config (core-site.xml).    The preferred method is using EC2 role and then requesting temporary credentials.
