### ISSUE TITLE
Document if and how EMR TASK nodes can be used by Spark

### ISSUE THREAD

**Issue by jkleckner** [awslabs/emr-bootstrap-actions#25]
Task nodes in EMR don't hold persistent data but can add compute power.  Can Spark take advantage of those?  If you run "hdfs dfsadmin -report" it won't enumerate the TASK nodes.

Similarly does Spark scale up with added CORE nodes?

**Comment by jkleckner** [comment]
Thank you.  It would be great to add this to the spark/README.md file.

**Comment by emanresusername** [comment]
this was all working fine pre emr 4.0.0 release, but on spark 1.4.1 with the emr 4.0.0 release it seems to only scale with the `CORE` nodes. any idea what caused this/how to get the old behavior back? @christopherbozeman

**Comment by ejono** [comment]
@emanresusername, are you the same person that posted as "javelin" on https://forums.aws.amazon.com/thread.jspa?messageID=662964? I am "jonathak" on the AWS forums. If that is indeed you, we can continue the discussion there.
