### ISSUE TITLE
Spark UI does not load with SSH tunnel

### ISSUE THREAD

**Issue by dunajevas** [awslabs/emr-bootstrap-actions#35]
I can access spark UI from command line via lynx, but with opened SSH tunnel the UI page does not load, I tried all possible link combinations localhost:4040, http://ec2-##-###-###-###.eu-west-1.compute.amazonaws.com:4040/, http://ip-##-##-###-###.eu-west-1.compute.internal. It is weird since I can access hadoop UIs on ports 9026 and 9101. I'm using AMI 3.3.1, with spark 1.2.0

**Comment by mhanisch** [comment]
I haven't verified it but it sounds like the Spark UI is bound to / listens on the local network interface only.
You might want to look into the web server config. 


--
Michael Hanisch
(sent from a mobile device, please excuse typos and brevity)

**Comment by dunajevas** [comment]
adding -g option to bootstrap action arguments fixes this issue
