### ISSUE TITLE
Spark 1.2 Configuration Incorrect

### ISSUE THREAD

**Issue by 8evers** [awslabs/emr-bootstrap-actions#41]
Hi,

I used the following settings to create a Spark 1.2 cluster, yet when I start spark shell, it is configured as a single node with 200 Mb of memory instead of a 5 node cluster with 28 Gb of memory per node

Steps

aws emr create-cluster --name MyCluster --ami-version 3.3.1 --instance-groups InstanceGroupType=MASTER,InstanceType=r3.xlarge,InstanceCount=1,BidPrice=0.32 InstanceGroupType=CORE,BidPrice=0.32,InstanceType=r3.xlarge,InstanceCount=5 --ec2-attributes KeyName=MyKey --applications Name=Hive Name=Impala Name=Hue --bootstrap-actions Path=s3://support.elasticmapreduce/spark/install-spark --steps Name=SparkHistoryServer,Jar=s3://elasticmapreduce/libs/script-runner/script-runner.jar,Args=s3://support.elasticmapreduce/spark/start-history-server 

/home/hadoop/spark/bin/spark-shell

I've also tried 
MASTER=yarn-client /home/hadoop/spark/bin/spark-shell
and
SPARK_MEM=28g /home/hadoop/spark/bin/spark-shell

My test script imports about 20Gb of data from S3 and runs some basic queries.  If I run it on non-emr cluster (created with the Spark ec2 scripts) I can do a simple count in < 20 seconds and cache all the data in memory.  Running the same scripts with these EMR Spark Scripts and the same ec2 instance types takes 10x longer.

It appear as if the scripts are not running across all nodes (or only on the master).  Is there more configuration I need to do?

**Comment by christopherbozeman** [comment]
The spark-shell will default to local and basic instance of Spark on EMR also uses the Spark defaults.   I recommend taking a look at the "-x" argument with "install-spark" at the readme https://github.com/awslabs/emr-bootstrap-actions/blob/master/spark/README.md.   This argument will preconfigure Spark to use the entire cluster as it was set at creation of the cluster.

Then try spark shell as:
MASTER=yarn-client /home/hadoop/spark/bin/spark-shell

**Comment by 8evers** [comment]
HI,

I did try the -x argument as well without any luck, however I suspect that this was related to issue 38  and the changes you made 3 hours ago seem to have fixed the issue

Thanks
