### ISSUE TITLE
install-spark should ignore case when searching for values

### ISSUE THREAD

**Issue by derrickburns** [awslabs/emr-bootstrap-actions#42]
the various "grep" calls in "maximize-spark-default-config" are searching for upper case values like "CORE" when the values are actually in mixed case if the user uses lower case to name instance groups.

**Comment by christopherbozeman** [comment]
Thanks for the report!   This is a duplicate of issue https://github.com/awslabs/emr-bootstrap-actions/issues/38.   Improvements have been made to "maximize-spark-default-config" use yarn node list instead of group based on name.

**Comment by christopherbozeman** [comment]
Derrick  - is this resolved?

**Comment by derrickburns** [comment]
Checking now.

BTW, how do I access ganglia for a spark cluster?  I seem to have forgotten
the magic.

**Comment by christopherbozeman** [comment]
Ganglia is on port 80 of the master node. `http://<masternode>/ganglia/`.   The specific Spark metrics appear under whichever node was running the driver.

**Comment by derrickburns** [comment]
thx!

**Comment by derrickburns** [comment]
That doesn't work for me on j-2Q17MKCBYWEJ7. Ideas?

**Comment by derrickburns** [comment]
Do I need to install ganglia with a bootstrap action? If so, how?

**Comment by christopherbozeman** [comment]
Yes, Ganglia has to be installed, too.  See http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/UsingEMR_Ganglia.html#init_Ganglia

**Comment by derrickburns** [comment]
Unfortunately, this page does not specify the bootstrap action to use when
NOT using the AWS command line tools (which I am not).   I tried using this
bootstrap action (run with the script-runner), but it failed:

s3://elasticmapreduce/bootstrap-actions/install-ganglia

Ideas?

**Comment by christopherbozeman** [comment]
I see. Just use 's3://elasticmapreduce/bootstrap-actions/install-ganglia'
as bootstrap without script runner.

**Comment by derrickburns** [comment]
Thx!
