### ISSUE TITLE
install-spark -x should set spark.yarn.executor.memoryOverhead for versions before 1.2

### ISSUE THREAD

**Issue by derrickburns** [awslabs/emr-bootstrap-actions#45]
Spark recommends a setting for spark.yarn.executor.memoryOverhead that is "executorMemory * 0.07, with minimum of 384".  This is default for 1.2.

**Comment by christopherbozeman** [comment]
Spark on EMR has been surpassed with native Spark on EMR and improved resource allocation (http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-spark-configure.html).
