### ISSUE TITLE
How is Spark for EMR constructed?  Is there a repo for it and can we build it?

### ISSUE THREAD

**Issue by jkleckner** [awslabs/emr-bootstrap-actions#67]
I have a test case that:

- Test case runs correctly locally when spark is built using sbt
- Test case fails locally when spark is built using mvn
- Test case runs correctly in Amazon versions 1.2.0.a and 1.2.1.a

Obviously the assembly created by maven is different from the one created by sbt.  For example, there is the ability to shade jar files with Maven that isn't possible in sbt and that is used by parquet-column (and perhaps other modules).

Are the Amazon versions built using maven or sbt?

Do you make a repo available for how those spark builds are created?

I would like to see how those are built to figure out what is going on.

For double bonus points, I would like to be able to roll my own spark installs to try out in EMR.

**Comment by christopherbozeman** [comment]
Currently, the Spark distribution is built with Maven.   See https://github.com/awslabs/emr-bootstrap-actions/blob/master/spark/examples/building-spark-for-emr.md for more details.

**Comment by christopherbozeman** [comment]
Yes, you can build your own distribution and use a custom `config.file` referenced with the `-c` argument to `install-spark` bootstrap-action for installation.

**Comment by jkleckner** [comment]
Thank you for documenting how to create a custom build.  The statement that the AWS build may be different from the distribution could be concerning.

Since you use maven for the build, the discrepancy I am seeing may be an OSX issue.

**Comment by jkleckner** [comment]
#71 is an example of how not knowing precisely the AWS build can create problems.
