### ISSUE TITLE
EMRFS using scopt for Scala 2.11 causing conflict with Spark running on 2.10

### ISSUE THREAD

**Issue by cmenguy** [awslabs/emr-bootstrap-actions#71]
I was having issues running my Spark program compiled for Spark 1.2.1 and Scala 2.10.

It turns out, on EMR Spark adds to its classpath the following jar: `/home/hadoop/spark/classpath/emrfs/scopt_2.11-3.2.0.jar`

If you're like me and not using 2.11, this is a cause of issues. To fix it, I add to add the scopt jar to the -u parameter to install-spark to add this jar in `/home/hadoop/spark/classpath/user-provided` and gets placed ahead of this other dependency.

I don't know much about EMRFS, but it seems like an issue given that it doesn't happen with Spark standalone.

**Comment by jkleckner** [comment]
Note that there are some 2.11 jars in hbase as well.  True on 1.2.0a, 1.2.1a, and 1.3.0a.
```
./.versions/spark-1.2.1.a/classpath/emrfs/scopt_2.11-3.2.0.jar
./.versions/hbase-0.94.18/lib/scopt_2.11-3.2.0.jar
./.versions/hbase-0.94.18/lib/scala-reflect-2.11.0.jar
./.versions/hbase-0.94.18/lib/scala-logging-api_2.11-2.1.2.jar
./.versions/hbase-0.94.18/lib/scala-library-2.11.0.jar
./.versions/hbase-0.94.18/lib/scala-logging-slf4j_2.11-2.1.2.jar
```

**Comment by christopherbozeman** [comment]
I see.. this is not an issue of the distribution build but of the install script.   Will look into it.

**Comment by mxk1235** [comment]
having the same issue.  it pretty much makes scopt unusable.  luckily we are not using any hbase stuff and were able to simply move the offending file and unblock our spark apps.

it definitely gets copied from  /usr/share/aws/emr/emrfs  by the install script  https://github.com/awslabs/emr-bootstrap-actions/blob/master/spark/archive_support_elasticmapreduce/1.2.0/install-spark-1.2.0.a.py#L55

i can't find the path "/usr/share/aws" on the emr master node, so i think it's a temporary path at bootstrap time.  an easy fix would be to check that location and remove the offending file from there, unless you are installing 2.11 of course.

**Comment by p7k** [comment]
@cmenguy 's workaround helps with direct `spark-submit`, however when I use a step it it gets executed via `hadoop jar /mnt/var/lib/hadoop/steps/s-<step-id>/script-runner.jar /home/hadoop/spark/bin/spark-submit` classpath changes seem to have no affect, and Spark jobs break with same `scopt` mismatch issues.

**Comment by cmenguy** [comment]
@p7k I was also using a `script-runner.jar` step and it seems the workaround of adding the `scopt_2.10.jar` to the `-u` option of the `install-spark` bootstrap action fixed it for me. Have you added it to the `-u` option or just created the `/home/hadoop/spark/classpath/user-provided` directory manually? `install-spark -u` also modifies the Spark config to include this `user-provided` directory in the `SPARK_CLASSPATH`, so if you did it manually this part may be missing.

**Comment by p7k** [comment]
@cmenguy i used the `-u` option and confirmed that `scopt` is in `spark/classpath/user-provided/` and that the classpath is adjusted accordingly in the config.
```
[hadoop@ip-10-157-108-238 ~]$ cat spark/conf/spark-env.sh | grep CLASS
export SPARK_CLASSPATH="/home/hadoop/spark/classpath/user-provided/*:/home/hadoop/spark/conf:/home/hadoop/conf:/home/hadoop/spark/classpath/emr/*:/home/hadoop/spark/classpath/emrfs/*:/home/hadoop/share/hadoop/common/lib/*:/home/hadoop/share/hadoop/common/lib/hadoop-lzo.jar"
```
After a bit more digging around - I've discovered that it's definitely associated with the `--master yarn-cluster` and `--deploy-mode cluster` flags that I set on my steps.  If those aren't provided everything runs smoothly.  Any insight regarding that?  What exactly would be the effect of not setting those options?

**Comment by cmenguy** [comment]
@p7k Weird, it seems like it worked fine for me with `--master yarn-client` and `--deploy-mode client`. Note that I only tried this with Spark 1.3 build 2015031101 (specified in `install-spark`), not with the 1.3 official release yet. Maybe @christopherbozeman can provide more context on why this would be different based on the master/deploy-mode, but from what I've tried it should work both ways.

**Comment by p7k** [comment]
@cmenguy , you're doing `client` I was trying with `cluster` ...

**Comment by christopherbozeman** [comment]
In regards to the Scala 2.11 libraries being picked up by the install script, it appears to me the script can safely removes these Scala 2.11 libraries without issue.  I would appreciate some help testing with your use-case to confirm (@cmenguy @p7k  @mxk1235 and @jkleckner).  Please use `-c s3://support.elasticmapreduce/spark/temp/issue71/config.file` (this will install 1.3.0.c only).

Here is the diff on the install-spark-script.py just doing a dump filter of Scala 2.11 libs.

```
95,96d94
<       scala_jars += glob.glob(emr_fs+"/*_2.11-*")
<       scala_jars += glob.glob(emr+"/*_2.11-*")
98,101c96
<               try:
<                       os.remove(jar)
<               except OSError:
<                       pass
---
>               os.remove(jar)
```

**Comment by jkleckner** [comment]
I spun up a cluster and it ran my tests.  But those tests didn't trip up on the scopt 2.11 jar before.

**Comment by christopherbozeman** [comment]
Thank you @jkleckner.

**Comment by christopherbozeman** [comment]
Resolved with https://github.com/awslabs/emr-bootstrap-actions/pull/98 by implementing code as stated above.
