### ISSUE TITLE
Upgrade spark installation to AMI 3.4.0, spark 1.3.1

### ISSUE THREAD

**Issue by jblomo** [awslabs/emr-bootstrap-actions#76]
I don't see these version in the config file, but they are the current versions.

**Comment by christopherbozeman** [comment]
It's available for AMI 3.4.0, just not the default. To request it use the -v argument to request 1.3.0.a

**Comment by jblomo** [comment]
Oh great, thank you!  I'll try it out, I must have missed the 'a'.
