### ISSUE TITLE
Update config file to install version 1.3.1

### ISSUE THREAD

**Issue by cqnguyen** [awslabs/emr-bootstrap-actions#92]
Can you update the install config file to install version 1.3.1 instead of 1.3.0.

Thanks,
Cory

**Comment by erond** [comment]
And maybe also update the support to Spark 1.2.x up to the latest available, i.e. 1.2.2. Thanks.

**Comment by christopherbozeman** [comment]
Spark 1.3.1 published. https://github.com/awslabs/emr-bootstrap-actions/pull/93
