### ISSUE TITLE
Update config file to install Spark version 1.2.2

### ISSUE THREAD

**Issue by erond** [awslabs/emr-bootstrap-actions#99]
Can you please update the install config file to install Spark version 1.2.2? Since such update is a maintenance/bugfix one I think it should be provided as the latest available for Spark 1.2.x.

Thanks,
erond

**Comment by christopherbozeman** [comment]
Done. See https://github.com/awslabs/emr-bootstrap-actions/pull/101

**Comment by erond** [comment]
Thank you very much!
